version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:latest

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-build

      - run: mix local.hex --force
      - run: mix deps.get

      # Make sure that compiled version works without build json available
      - run: MIX_ENV=test mix compile
      - run: rm _build/test/lib/ex_cldr/priv/cldr/territory_containment.json

      - run: mix test

      - save_cache:
          key: deps-build
          paths:
            - ~/repo/_build
            - ~/repo/deps
